routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');


Route::group(['prefix' => 'admin', 'middleware' => 'role:admin'], function() {

    Route::resource('users', 'App\Http\Controllers\Admin\UsersController');

    Route::put('users/roles/{user}', 'App\Http\Controllers\Admin\UsersController@roles')
        ->name('users.roles');

    Route::resource('news', 'App\Http\Controllers\Admin\NewsController');
    Route::resource('categories', 'App\Http\Controllers\Admin\CategoriesController');

});

Route::group(['prefix' => 'admin'], function() {

    Route::resource('profile', 'App\Http\Controllers\Admin\ProfileController')->only(['index']);

});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/User.php
<?php

namespace App\Models;

use App\Traits\HasRolesAndPermissions;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Tymon\JWTAuth\Contracts\JWTSubject;

class User extends Authenticatable implements JWTSubject
{
    use HasFactory, Notifiable, HasRolesAndPermissions;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * Get the identifier that will be stored in the subject claim of the JWT.
     *
     * @return mixed
     */
    public function getJWTIdentifier()
    {
        return $this->getKey();
    }

    /**
     * Return a key value array, containing any custom claims to be added to the JWT.
     *
     * @return array
     */
    public function getJWTCustomClaims()
    {
        return [];
    }
}

app/Http/Controllers/Admin/UsersController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Requests\NewsSearchRequest;
use App\Http\Requests\UserPasswordRequest;
use App\Http\Requests\UserStoreRequest;
use App\Http\Requests\UserUpdateRequest;
use App\Models\Role;
use App\Models\User;
use App\Models\UserRole;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\Session;

/**
 * Class UsersController
 * @package App\Http\Controllers\Admin
 */
class UsersController extends AdminController
{

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function index()
    {
        $users = User::paginate(10);

        return view('admin.users.index', [
            'users' => $users
        ]);
    }

    /**
     * @param NewsSearchRequest $newsSearchRequest
     * @return \Illuminate\Http\JsonResponse
     */
    public function create()
    {
        $roles = Role::all();
        return view('admin.users.create', [
            'roles' => $roles
        ]);
    }

    /**
     * @param User $user
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function edit(User $user)
    {
        $roles = Role::all();
        return view('admin.users.update', [
            'user' => $user,
            'roles' => $roles
        ]);
    }

    /**
     * @param UserStoreRequest $userStoreRequest
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(UserStoreRequest $userStoreRequest)
    {
        $user = new User();

        $data = $userStoreRequest->validated();

        $user->fill($data);
        $user->password = Hash::make($user->password);

        $user->save();

        if(!empty($data['roles'])) {
            foreach ($data['roles'] as $id) {
                $role = Role::where('id', $id)->first();

                $user->roles()->attach($role);
            }
        }

        return Redirect::to('/admin/users');

    }

    /**
     * @param UserUpdateRequest $userUpdateRequest
     * @param User $user
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(UserUpdateRequest $userUpdateRequest, User $user)
    {
        $data = $userUpdateRequest->validated();

        $user->fill($data);
        $user->password = Hash::make($user->password);

        $user->save();

        Session::flash('message', 'Успешно обновлено');

        return Redirect::to('/admin/users');

    }

    /**
     * @param UserPasswordRequest $userPasswordRequest
     * @param User $user
     * @return \Illuminate\Http\RedirectResponse
     */
    public function roles(UserPasswordRequest $userPasswordRequest, User $user)
    {
        $data = $userPasswordRequest->validated();

        if(!empty($data['roles'])) {
            UserRole::where('user_id', $user->id)->delete();

            foreach ($data['roles'] as $id) {
                $role = Role::where('id', $id)->first();

                $user->roles()->attach($role);
            }
        }
        Session::flash('message', 'Успешно обновлено');

        return Redirect::to('/admin/users');

    }

    /**
     * @param User $user
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function show(User $user)
    {
        return view('admin.users.show', [
            'user' => $user
        ]);
    }

    /**
     * @param User $user
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Exception
     */
    public function destroy(User $user)
    {
        $user->delete();
        Session::flash('message', 'Успешно удалено');

        return Redirect::to('/admin/users');
    }

}

resources/views/admin/users/create.blade.php
@extends('adminlte::page')

@section('title', 'Создание пользователя')

@section('content_header')
    <h1>Создание пользователя</h1>
@stop



@section('content')

    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif


    <form action="{{ route('users.store') }}" method="POST" class="form" enctype="multipart/form-data">

        @csrf

        <div class="form-group">
            <label for="name">
                Имя
            </label>

            <input type="text" class="form-control" name="name" placeholder="Имя" value="{{old('name')}}"/>
        </div>

        <div class="form-group">
            <label for="name">
                Email
            </label>

            <input type="text" class="form-control" name="email" placeholder="Email" value="{{old('email')}}"/>
        </div>

        <div class="form-group">
            <label for="name">
                Пароль
            </label>

            <input type="password" class="form-control" name="password" placeholder="Пароль" value="{{old('password')}}"/>
        </div>

        <div class="form-group">
            <label for="name">
                Подтверждение пароля
            </label>

            <input type="password" class="form-control" name="password_confirmation" placeholder="Подтверждение пароля" value="{{old('password_confirmation')}}"/>
        </div>


        @if (count($roles) > 0)
            <h3>
                Роли
            </h3>
            @foreach ($roles as $key => $role)
                <div class="form-group">
                    <input type="checkbox" id="role{{$role->id}}" name="roles[]" value="{{$role->id}}"/>
                    <label for="role{{$role->id}}">
                        {{$role->name}}
                    </label>
                </div>
            @endforeach
        @endif


        <button type="submit" class="btn btn-primary">
            Создать
        </button>

    </form>

@endsection

resources/views/admin/users/index.blade.php
@extends('adminlte::page')

@section('title', 'Пользователи')

@section('content_header')
    <h1>Пользователи</h1>
@stop

@section('content')

    @if (Session::has('message'))
        <div class="alert alert-info">
            {{ Session::get('message') }}
        </div>
    @endif

    @if (Session::has('error'))
        <div class="alert alert-danger">
            {{ Session::get('error') }}
        </div>
    @endif

    <div class="row">
        <div class="col-12">
            <a class="btn btn-small btn-success" href="{{URL::to('/admin/users/create')}}">
                Создать пользователя
            </a>
        </div>
    </div>

    <br/>

    <table class="table table-striped table-bordered">
        <thead>
        <tr>
            <td>ID</td>
            <td>Логин</td>
            <td>Имя</td>
            <td>
                Кнопки
            </td>
        </tr>
        </thead>
        <tbody>
            @foreach($users as $key => $user)
                <tr>
                    <td>
                        {{ $user->id }}
                    </td>
                    <td>
                        {{ $user->email }}
                    </td>
                    <td>
                        {{ $user->name }}
                    </td>

                    <td>

                        <a href="{{ route('users.show',$user->id)  }}" style="float:left">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-eye" viewBox="0 0 16 16">
                                <path d="M16 8s-3-5.5-8-5.5S0 8 0 8s3 5.5 8 5.5S16 8 16 8zM1.173 8a13.133 13.133 0 0 1 1.66-2.043C4.12 4.668 5.88 3.5 8 3.5c2.12 0 3.879 1.168 5.168 2.457A13.133 13.133 0 0 1 14.828 8c-.058.087-.122.183-.195.288-.335.48-.83 1.12-1.465 1.755C11.879 11.332 10.119 12.5 8 12.5c-2.12 0-3.879-1.168-5.168-2.457A13.134 13.134 0 0 1 1.172 8z"></path>
                                <path d="M8 5.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5zM4.5 8a3.5 3.5 0 1 1 7 0 3.5 3.5 0 0 1-7 0z"></path>
                            </svg>
                        </a>

                        <a href="{{ route('users.edit',$user->id) }}" style="float:left">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-fill" viewBox="0 0 16 16">
                                <path d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708l-3-3zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207l6.5-6.5zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.499.499 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11l.178-.178z"></path>
                            </svg>
                        </a>

                        <form action="{{ route('users.destroy', $user->id) }}" method="POST" style="float:left">
                            @csrf
                            @method('DELETE')

                            <button type="submit" style="border: none;">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                                    <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"></path>
                                    <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"></path>
                                </svg>
                            </button>
                        </form>

                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>


    {{ $users->links('vendor.pagination.bootstrap-4') }}


@endsection

resources/views/admin/users/show.blade.php
@extends('adminlte::page')

@section('title', 'Просмотр пользователя')

@section('content_header')
    <h1>Просмотр пользователя</h1>
@stop



@section('content')

    <h3>
        Имя
    </h3>

    <div>
        {{$user->name}}
    </div>

    <h3>
        Email
    </h3>

    <div>
        {{$user->email}}
    </div>


    <h3>
        Роли
    </h3>

    <div>
        @foreach ($user->roles as $key => $role)
            {{$role->name}}@if($key != count($user->roles)-1),@endif
        @endforeach
    </div>

@endsection

resources/views/admin/users/update.blade.php
@extends('adminlte::page')

@section('title', 'Редактирование пользователя')

@section('content_header')
    <h1>Редактирование пользователя</h1>
@stop

@section('content')

    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif


    <form action="{{ route('users.update', $user->id) }}" method="POST" class="form" enctype="multipart/form-data">

        @csrf
        @method('PUT')

        <div class="form-group">
            <label for="name">
                Имя
            </label>

            <input type="text" class="form-control" name="name" placeholder="Имя" value="{{$user->name}}"/>
        </div>

        <div class="form-group">
            <label for="name">
                Email
            </label>

            <input type="text" class="form-control" name="email" placeholder="Email" value="{{$user->email}}"/>
        </div>

        <div class="form-group">
            <label for="name">
                Пароль
            </label>

            <input type="password" class="form-control" name="password" placeholder="Пароль" />
        </div>

        <div class="form-group">
            <label for="name">
                Подтверждение пароля
            </label>

            <input type="password" class="form-control" name="password_confirmation" placeholder="Подтверждение пароля" />
        </div>

        <button type="submit" class="btn btn-primary">
            Создать
        </button>
    </form>


    <form action="{{ route('users.roles', $user->id) }}" method="POST" class="form" enctype="multipart/form-data">

        @csrf
        @method('PUT')

        @if (count($roles) > 0)
            <h3>
                Роли
            </h3>
            @foreach ($roles as $key => $role)
                <div class="form-group">
                    <input @foreach($user->roles as $userRole) @if($userRole->id == $role->id) checked @endif @endforeach type="checkbox" id="role{{$role->id}}" name="roles[]" value="{{$role->id}}"/>
                    <label for="role{{$role->id}}">
                        {{$role->name}}
                    </label>
                </div>
            @endforeach
        @endif


        <button type="submit" class="btn btn-primary">
            Создать
        </button>
    </form>


@endsection