routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');


Route::group(['prefix' => 'admin', 'middleware' => 'role:admin'], function() {

    Route::resource('users', 'App\Http\Controllers\Admin\UsersController');

    Route::put('users/roles/{user}', 'App\Http\Controllers\Admin\UsersController@roles')
        ->name('users.roles');

    Route::resource('news', 'App\Http\Controllers\Admin\NewsController');
    Route::resource('categories', 'App\Http\Controllers\Admin\CategoriesController');

});

Route::group(['prefix' => 'admin'], function() {

    Route::resource('profile', 'App\Http\Controllers\Admin\ProfileController')->only(['index']);

});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class Category
 * @package App\Models
 */
class Category extends Model
{
    use HasFactory;
    use SoftDeletes;

    /**
     * @var string
     */
    protected $table = 'category';

    /**
     * @var array
     */
    protected $fillable = [
        'name',
        'parent_id'
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function newses()
    {
        return $this->belongsToMany('App\Models\News', 'news_category');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function parent()
    {
        return $this->belongsTo('App\Models\Category', 'parent_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function children()
    {
        return $this->hasMany('App\Models\Category', 'parent_id', 'id');
    }
}

app/Http/Controllers/Admin/CategoriesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Requests\CategoryStoreRequest;
use App\Http\Requests\CategoryUpdateRequest;
use App\Http\Requests\NewsSearchRequest;
use App\Models\Category;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\Session;

/**
 * Class CategoriesController
 * @package App\Http\Controllers\Admin
 */
class CategoriesController extends AdminController
{

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function index()
    {
        $categories = Category::paginate(10);


        return view('admin.categories.index', [
            'categories' => $categories
        ]);
    }

    /**
     * @param NewsSearchRequest $newsSearchRequest
     * @return \Illuminate\Http\JsonResponse
     */
    public function create()
    {
        $categories = Category::all();
        return view('admin.categories.create', [
            'categories' => $categories
        ]);
    }

    /**
     * @param Category $category
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function edit(Category $category)
    {
        $categories = Category::all();
        return view('admin.categories.update', [
            'category' => $category,
            'categories' => $categories
        ]);
    }

    /**
     * @param CategoryStoreRequest $categoryStoreRequest
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(CategoryStoreRequest $categoryStoreRequest)
    {
        $category = new Category();

        $data = $categoryStoreRequest->validated();

        $category->fill($data);

        $category->save();

        return Redirect::to('/admin/categories');

    }

    /**
     * @param CategoryUpdateRequest $categoryUpdateRequest
     * @param Category $category
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(CategoryUpdateRequest $categoryUpdateRequest, Category $category)
    {
        $data = $categoryUpdateRequest->validated();
        $category->fill($data);

        $category->save();

        return Redirect::to('/admin/categories');

    }

    /**
     * @param Category $category
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function show(Category $category)
    {
        return view('admin.categories.show', [
            'category' => $category
        ]);
    }

    /**
     * @param Category $category
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Exception
     */
    public function destroy(Category $category)
    {
        if($category->newses()->count()) {
            Session::flash('error', 'Есть связанные новости');
        } else if($category->children()->count()) {
            Session::flash('error', 'Есть связанные категории');
        } else {
            $category->delete();
            Session::flash('message', 'Успешно удалено');
        }

        return Redirect::to('/admin/categories');
    }

}

resources/views/admin/categories/create.blade.php
@extends('adminlte::page')

@section('title', 'Создание категории')

@section('content_header')
    <h1>Создание категории</h1>
@stop

@section('content')

    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif


    <form action="{{ route('categories.store') }}" method="POST" class="form" enctype="multipart/form-data">

        @csrf

        <div class="form-group">
            <label for="name">
                Название
            </label>

            <input type="text" class="form-control" id="name" name="name" placeholder="Название" value="{{old('name')}}"/>
        </div>

        @if (count($categories) > 0)
            <div class="form-group">
                <label for="detail_text">
                    Родительская категория
                </label>
                <br/>
                <select name="parent_id">
                    <option></option>
                    @foreach ($categories as $category)
                        <option value="{{$category->id}}">
                            {{$category->name}}
                        </option>
                    @endforeach
                </select>
            </div>
        @endif


        <button type="submit" class="btn btn-primary">
            Создать
        </button>

    </form>

@endsection

resources/views/admin/categories/index.blade.php
@extends('adminlte::page')

@section('title', 'Категории')

@section('content_header')
    <h1>Категории</h1>
@stop

@section('content')

    @if (Session::has('message'))
        <div class="alert alert-info">
            {{ Session::get('message') }}
        </div>
    @endif

    @if (Session::has('error'))
        <div class="alert alert-danger">
            {{ Session::get('error') }}
        </div>
    @endif

    <div class="row">
        <div class="col-12">
            <a class="btn btn-small btn-success" href="{{URL::to('/admin/categories/create')}}">
                Создать категорию
            </a>
        </div>
    </div>

    <br/>

    <table class="table table-striped table-bordered">
        <thead>
        <tr>
            <td>ID</td>
            <td>Название</td>
            <td>Родитель</td>
            <td>
                Кнопки
            </td>
        </tr>
        </thead>
        <tbody>
            @foreach($categories as $key => $category)
                <tr>
                    <td>
                        {{ $category->id }}
                    </td>
                    <td>
                        {{ $category->name }}
                    </td>
                    <td>
                        @if($category->parent)
                            {{$category->parent->name}}
                        @endif
                    </td>

                    <td>

                        <a href="{{ route('categories.show',$category->id)  }}" style="float:left">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-eye" viewBox="0 0 16 16">
                                <path d="M16 8s-3-5.5-8-5.5S0 8 0 8s3 5.5 8 5.5S16 8 16 8zM1.173 8a13.133 13.133 0 0 1 1.66-2.043C4.12 4.668 5.88 3.5 8 3.5c2.12 0 3.879 1.168 5.168 2.457A13.133 13.133 0 0 1 14.828 8c-.058.087-.122.183-.195.288-.335.48-.83 1.12-1.465 1.755C11.879 11.332 10.119 12.5 8 12.5c-2.12 0-3.879-1.168-5.168-2.457A13.134 13.134 0 0 1 1.172 8z"></path>
                                <path d="M8 5.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5zM4.5 8a3.5 3.5 0 1 1 7 0 3.5 3.5 0 0 1-7 0z"></path>
                            </svg>
                        </a>

                        <a href="{{ route('categories.edit',$category->id) }}" style="float:left">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-fill" viewBox="0 0 16 16">
                                <path d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708l-3-3zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207l6.5-6.5zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.499.499 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11l.178-.178z"></path>
                            </svg>
                        </a>

                        <form action="{{ route('categories.destroy', $category->id) }}" method="POST" style="float:left">
                            @csrf
                            @method('DELETE')

                            <button type="submit" style="border: none;">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                                    <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"></path>
                                    <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"></path>
                                </svg>
                            </button>
                        </form>

                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>


    {{ $categories->links('vendor.pagination.bootstrap-4') }}


@endsection

resources/views/admin/categories/show.blade.php
@extends('adminlte::page')

@section('title', $category->name)

@section('content_header')
    <h1>{{$category->name}}</h1>
@stop

@section('content')

    @if($category->parent)
        <h2>
            Родитель
        </h2>

        <div>
            {{$category->parent->name}}
        </div>
    @endif

@endsection

resources/views/admin/categories/update.blade.php
@extends('adminlte::page')

@section('title', 'Редактирование категории')

@section('content_header')
    <h1>Редактирование категории</h1>
@stop

@section('content')

    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif


    <form action="{{ route('categories.update', $category->id) }}" method="POST" class="form" enctype="multipart/form-data">

        @csrf
        @method('PUT')

        <div class="form-group">
            <label for="name">
                Название
            </label>

            <input type="text" class="form-control" id="name" name="name" placeholder="Название" value="{{$category->name}}"/>
        </div>

        @if (count($categories) > 0)
            <div class="form-group">
                <label for="detail_text">
                    Родительская категория
                </label>
                <select name="parent_id">
                    <option>
                    </option>
                    @foreach ($categories as $model)
                        <option @if($model->id == $category->parent_id) selected @endif
                                value="{{$model->id}}">

                            {{$model->name}}
                        </option>
                    @endforeach
                </select>
            </div>
        @endif

        <button type="submit" class="btn btn-primary">
            Сохранить
        </button>

    </form>

@endsection