routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');


Route::group(['prefix' => 'admin', 'middleware' => 'role:admin'], function() {

    Route::resource('users', 'App\Http\Controllers\Admin\UsersController');

    Route::put('users/roles/{user}', 'App\Http\Controllers\Admin\UsersController@roles')
        ->name('users.roles');

    Route::resource('news', 'App\Http\Controllers\Admin\NewsController');
    Route::resource('categories', 'App\Http\Controllers\Admin\CategoriesController');

});

Route::group(['prefix' => 'admin'], function() {

    Route::resource('profile', 'App\Http\Controllers\Admin\ProfileController')->only(['index']);

});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/News.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class News
 * @package App\Models
 */
class News extends Model
{

    use HasFactory;
    use SoftDeletes;

    /**
     * @var string
     */
    protected $table = 'news';

    /**
     * @var array
     */
    protected $fillable = [
        'name',
        'preview_img',
        'preview_text',
        'detail_img',
        'detail_text'
    ];


    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function categories()
    {
        return $this->belongsToMany('App\Models\Category', 'news_category');
    }
}

app/Http/Controllers/Admin/NewsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Requests\NewsSearchRequest;
use App\Http\Requests\NewsStoreRequest;
use App\Http\Requests\NewsUpdateRequest;
use App\Models\Category;
use App\Models\News;
use App\Models\NewsCategory;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\Session;

/**
 * Class NewsController
 * @package App\Http\Controllers\Api
 */
class NewsController extends AdminController
{

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * @param NewsSearchRequest $newsSearchRequest
     * @return \Illuminate\Http\JsonResponse
     */
    public function index()
    {
        $newses = News::paginate(10);


        return view('admin.news.index', [
            'newses' => $newses
        ]);
    }

    /**
     * @param NewsSearchRequest $newsSearchRequest
     * @return \Illuminate\Http\JsonResponse
     */
    public function create()
    {
        $categories = Category::all();
        return view('admin.news.create', [
            'categories' => $categories
        ]);
    }

    /**
     * @param NewsCreateRequest $newsCreateRequest
     * @param News $news
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function edit(News $news)
    {
        $categories = Category::all();

        return view('admin.news.update', [
            'news' => $news,
            'categories' => $categories
        ]);
    }

    /**
     * @param NewsStoreRequest $newsStoreRequest
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(NewsStoreRequest $newsStoreRequest)
    {
        $news = new News();

        $data = $newsStoreRequest->validated();

        $news->fill($data);

        if($newsStoreRequest->hasFile('preview_img')) {
            $file = $newsStoreRequest->file('preview_img');
            $file->move(public_path() . '/img/news/', $file->getClientOriginalName());

            $news->preview_img = '/img/news/'.$file->getClientOriginalName();
        }

        if($newsStoreRequest->hasFile('detail_img')) {
            $file = $newsStoreRequest->file('detail_img');
            $file->move(public_path() . '/img/news/', $file->getClientOriginalName());

            $news->detail_img = '/img/news/'.$file->getClientOriginalName();
        }

        $news->save();

        if(!empty($data['categories'])) {
            foreach ($data['categories'] as $id) {
                $category = new NewsCategory();
                $category->news_id = $news->id;
                $category->category_id = $id;
                $category->save();
            }
        }

        return Redirect::to('/admin/news/');

    }

    /**
     * @param NewsUpdateRequest $newsUpdateRequest
     * @param News $news
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(NewsUpdateRequest $newsUpdateRequest, News $news)
    {
        $data = $newsUpdateRequest->validated();
        $news->fill($data);

        if($newsUpdateRequest->hasFile('preview_img')) {
            $file = $newsUpdateRequest->file('preview_img');
            $file->move(public_path() . '/img/news/', $file->getClientOriginalName());

            if(file_exists(public_path().$news->preview_img)) {
                unlink(public_path() . $news->preview_img);
            }

            $news->preview_img = '/img/news/'.$file->getClientOriginalName();
        }

        if($newsUpdateRequest->hasFile('detail_img')) {
            $file = $newsUpdateRequest->file('detail_img');
            $file->move(public_path() . '/img/news/', $file->getClientOriginalName());

            if(file_exists(public_path().$news->detail_img)) {
                unlink(public_path().$news->detail_img);
            }


            $news->detail_img = '/img/news/'.$file->getClientOriginalName();
        }

        $news->save();

        if(!empty($data['categories'])) {
            NewsCategory::where('news_id', $news->id)->delete();

            foreach ($data['categories'] as $id) {
                $category = new NewsCategory();
                $category->news_id = $news->id;
                $category->category_id = $id;
                $category->save();
            }
        }

        return Redirect::to('/admin/news/');

    }

    /**
     * @param News $news
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function show(News $news)
    {
        return view('admin.news.show', [
            'news' => $news
        ]);
    }


    public function destroy(News $news)
    {

        $news->categories()->delete();

        if(file_exists(public_path().$news->preview_img)) {
            unlink(public_path() . $news->preview_img);
        }

        if(file_exists(public_path().$news->detail_img)) {
            unlink(public_path().$news->detail_img);
        }

        $news->delete();

        Session::flash('message', 'Успешно удалено');
        return Redirect::to('/admin/news');
    }

}

resources/views/admin/news/create.blade.php
@extends('adminlte::page')

@section('title', 'Создание новости')

@section('content_header')
    <h1>Создание новости</h1>
@stop

@section('content')

    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif


    <form action="{{ route('news.store') }}" method="POST" class="form" enctype="multipart/form-data">

        @csrf

        <div class="form-group">
            <label for="name">
                Название
            </label>

            <input type="text" class="form-control" id="name" name="name" placeholder="Название" value="{{old('name')}}"/>
        </div>

        <div class="form-group">
            <label for="preview_img">Картинка анонса</label>
            <input type="file" name="preview_img" class="form-control-file" id="preview_img">
        </div>

        <div class="form-group">
            <label for="preview_text">
                Текст анонса
            </label>
            <textarea class="form-control" id="preview_text" name="preview_text" placeholder="Анонс" >{{old('preview_text')}}</textarea>
        </div>

        <div class="form-group">
            <label for="detail_img">Детальная картинка</label>
            <input type="file" name="detail_img" class="form-control-file" id="detail_img">
        </div>

        <div class="form-group">
            <label for="detail_text">
                Детальный тект
            </label>
            <textarea  class="form-control" id="detail_text" name="detail_text" placeholder="Детальный текст" >{{old('detail_text')}}</textarea>
        </div>

        @if (count($categories) > 0)
            @php
                $config = [
                    'placeholder' => 'Выберите категорию',
                    'allowClear' => true
                ];
            @endphp
            <x-adminlte-select2 id="categories" name="categories[]" label="Категории"
                                size="sm" :config="$config" multiple>
                @foreach ($categories as $category)
                    <option value="{{$category->id}}">
                        {{$category->name}}
                    </option>
                @endforeach
            </x-adminlte-select2>

        @endif


        <button type="submit" class="btn btn-primary">
            Создать
        </button>

    </form>

@endsection

resources/views/admin/news/index.blade.php
@extends('adminlte::page')

@section('title', 'Новости')

@section('content_header')
    <h1>Новости</h1>
@stop

@section('content')

    @if (Session::has('message'))
        <div class="alert alert-info">
            {{ Session::get('message') }}
        </div>
    @endif

    <div class="row">
        <div class="col-12">
            <a class="btn btn-small btn-success" href="{{URL::to('/admin/news/create')}}">
                Создать новость
            </a>
        </div>
    </div>

    <br/>

    <table class="table table-striped table-bordered">
        <thead>
        <tr>
            <td>ID</td>
            <td>Название</td>
            <td>Картинка анонса</td>
            <td>Анонс текст</td>
            <td>
                Кнопки
            </td>
        </tr>
        </thead>
        <tbody>
            @foreach($newses as $key => $news)
                <tr>
                    <td>
                        {{ $news->id }}
                    </td>
                    <td>
                        {{ $news->name }}
                    </td>
                    <td>
                        <img width="200" src="{{ $news->preview_img }}" />
                    </td>
                    <td>
                        {{ $news->preview_text }}
                    </td>

                    <td>

                        <a href="{{ route('news.show',$news->id)  }}" style="float:left">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-eye" viewBox="0 0 16 16">
                                <path d="M16 8s-3-5.5-8-5.5S0 8 0 8s3 5.5 8 5.5S16 8 16 8zM1.173 8a13.133 13.133 0 0 1 1.66-2.043C4.12 4.668 5.88 3.5 8 3.5c2.12 0 3.879 1.168 5.168 2.457A13.133 13.133 0 0 1 14.828 8c-.058.087-.122.183-.195.288-.335.48-.83 1.12-1.465 1.755C11.879 11.332 10.119 12.5 8 12.5c-2.12 0-3.879-1.168-5.168-2.457A13.134 13.134 0 0 1 1.172 8z"></path>
                                <path d="M8 5.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5zM4.5 8a3.5 3.5 0 1 1 7 0 3.5 3.5 0 0 1-7 0z"></path>
                            </svg>
                        </a>

                        <a href="{{ route('news.edit',$news->id) }}" style="float:left">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-fill" viewBox="0 0 16 16">
                                <path d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708l-3-3zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207l6.5-6.5zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.499.499 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11l.178-.178z"></path>
                            </svg>
                        </a>

                        <form action="{{ route('news.destroy', $news->id) }}" method="POST" style="float:left">
                            @csrf
                            @method('DELETE')

                            <button type="submit" style="border: none;">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                                    <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"></path>
                                    <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"></path>
                                </svg>
                            </button>
                        </form>

                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>

    {{ $newses->links('vendor.pagination.bootstrap-4') }}

@endsection

resources/views/admin/news/show.blade.php
@extends('adminlte::page')

@section('title', 'Новость')

@section('content_header')
    <h1>Новость</h1>
@stop

@section('content')

    <h1>{{$news->name}}</h1>

    <h2>
        Картинка Анонса
    </h2>

    <div>
        <img width="200" src="{{$news->preview_img}}" />
    </div>

    <h2>
        Текст анонса
    </h2>

    <div>
        {{$news->preview_text}}
    </div>

    <h2>
        Картинка Детальная
    </h2>

    <div>
        <img width="200" src="{{$news->detail_img}}" />
    </div>

    <h2>
        Детальный текс
    </h2>

    <div>
        {{$news->preview_text}}
    </div>

@endsection

resources/views/admin/news/update.blade.php
@extends('adminlte::page')

@section('title', 'Редактирование новости')

@section('content_header')
    <h1>Редактирование новости</h1>
@stop
@section('content')

    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif


    <form action="{{ route('news.update', $news->id) }}" method="POST" class="form" enctype="multipart/form-data">

        @csrf
        @method('PUT')

        <div class="form-group">
            <label for="name">
                Название
            </label>

            <input type="text" class="form-control" id="name" name="name" placeholder="Название" value="{{$news->name}}"/>
        </div>

        <img width="200" src="{{$news->preview_img}}" />

        <div class="form-group">
            <label for="preview_img">Картинка анонса</label>
            <input type="file" name="preview_img" class="form-control-file" id="preview_img">
        </div>

        <div class="form-group">
            <label for="preview_text">
                Текст анонса
            </label>
            <textarea class="form-control" id="preview_text" name="preview_text" placeholder="Анонс" >{{$news->preview_text}}</textarea>
        </div>

        <img width="200" src="{{$news->detail_img}}" />

        <div class="form-group">
            <label for="detail_img">Детальная картинка</label>
            <input type="file" name="detail_img" class="form-control-file" id="detail_img">
        </div>

        <div class="form-group">
            <label for="detail_text">
                Детальный тект
            </label>
            <textarea  class="form-control" id="detail_text" name="detail_text" placeholder="Детальный текст" >{{$news->detail_text}}</textarea>
        </div>


        @if (count($categories) > 0)
            @php
                $config = [
                    'placeholder' => 'Выберите категорию',
                    'allowClear' => true
                ];
            @endphp
            <x-adminlte-select2 id="categories" name="categories[]" label="Категории"
                                size="sm" :config="$config" multiple>
                @foreach ($categories as $category)
                    <option @foreach($news->categories as $newsCategory) @if($newsCategory->id == $category->id) selected @endif @endforeach
                            value="{{$category->id}}">

                        {{$category->name}}
                    </option>
                @endforeach
            </x-adminlte-select2>

        @endif

        <button type="submit" class="btn btn-primary">
            Сохранить
        </button>

    </form>

@endsection